# 환경 변수 파일 import
spring.config.import=optional:file:.env[.properties]

# 웹 설정
server.port=8080

# 데이터소스 설정
spring.datasource.url=jdbc:mysql://${DATASOURCE_HOST}?useUniCode=yes&characterEncoding=UTF-8
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PWD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 설정
spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

naver.client.id=tIJiHiTbQ4V7r9vN3A25
naver.client.secret=39ba4QdL7C
naver.redirect.uri=http://localhost:8080/api/naver/callback

spring.sql.init.mode=always

#SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ticketopenwave@gmail.com
spring.mail.password=mkbcidnrtzlyvwng
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#cookie
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true